version: "3"
services: 
    api:
        build: .
        depends_on:
            - postgres
        volumes:
            - .:/usr/src/app:ro
        ports:
            - "8000:8000" # port on localhost : port on container
        env_file:
            - .env
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=twitter
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=402352def085e7dc747d9f17c9ac190c8e3de806520bde804e3cdc8d33025106
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        command: ["./entrypoint.sh"]
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=twitter
            
        volumes:
            - postgres-db:/var/lib/postgresql/data/
volumes:
    postgres-db: 
